# .github/workflows/build-prerelease.yml
name: Build Prerelease

on:
  push:
    branches: [master, dev]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [bun-linux-x64, bun-darwin-x64, bun-windows-x64]
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - name: Install dependencies
        run: bun install
      - name: Run build script for ${{ matrix.target }}
        run: bun run build --target ${{ matrix.target }}
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: unipm-prerelease-${{ matrix.target }}
          path: ./out/
